//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Systems Context/InputSystem/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Computer"",
            ""id"": ""57674850-5769-4e59-8fe5-d971c56a9302"",
            ""actions"": [
                {
                    ""name"": ""LeftFlipper"",
                    ""type"": ""Value"",
                    ""id"": ""936e10ba-139c-4b20-a2fd-0f657311cdad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightFlipper"",
                    ""type"": ""Button"",
                    ""id"": ""0c973f19-6a68-4759-81a0-1143e0ba6977"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spring"",
                    ""type"": ""Button"",
                    ""id"": ""c8270b31-b788-4646-b8e9-479083104d5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability"",
                    ""type"": ""Button"",
                    ""id"": ""20e09149-4ea6-485e-a515-8c4d5466cd6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""912d4db6-3c3b-4bb6-8107-4a2f132a94d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""5b7336f8-b8cf-4e15-baba-e3ff4b02e7cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dab5e23e-7584-4939-9464-d08cde34c8ce"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Spring"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c310f07-8d03-43f4-9d51-9db5420a77b5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Spring"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b32a4df-aa81-42e3-bb4c-6d131d847ef8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1718793-b954-4c77-84db-a2625b2d2278"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08e87c78-4f34-4dea-92e2-9a7fd665a25c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Hold(duration=3)"",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5167875-b1d4-4e0b-beea-b4d1839f31e6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42584bf6-575c-4b6a-b678-7a28a65cb6fb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""LeftFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f8b0055-268c-4a9f-9462-0550df09e447"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""LeftFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d5b0e93-7b92-494f-ad77-96816e2a2a9a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""RightFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83050fea-e0a4-48df-aba5-3c768b73ea77"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""RightFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Computer"",
            ""bindingGroup"": ""Computer"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Computer
        m_Computer = asset.FindActionMap("Computer", throwIfNotFound: true);
        m_Computer_LeftFlipper = m_Computer.FindAction("LeftFlipper", throwIfNotFound: true);
        m_Computer_RightFlipper = m_Computer.FindAction("RightFlipper", throwIfNotFound: true);
        m_Computer_Spring = m_Computer.FindAction("Spring", throwIfNotFound: true);
        m_Computer_Ability = m_Computer.FindAction("Ability", throwIfNotFound: true);
        m_Computer_Skip = m_Computer.FindAction("Skip", throwIfNotFound: true);
        m_Computer_Pause = m_Computer.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Computer
    private readonly InputActionMap m_Computer;
    private IComputerActions m_ComputerActionsCallbackInterface;
    private readonly InputAction m_Computer_LeftFlipper;
    private readonly InputAction m_Computer_RightFlipper;
    private readonly InputAction m_Computer_Spring;
    private readonly InputAction m_Computer_Ability;
    private readonly InputAction m_Computer_Skip;
    private readonly InputAction m_Computer_Pause;
    public struct ComputerActions
    {
        private @PlayerInputs m_Wrapper;
        public ComputerActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftFlipper => m_Wrapper.m_Computer_LeftFlipper;
        public InputAction @RightFlipper => m_Wrapper.m_Computer_RightFlipper;
        public InputAction @Spring => m_Wrapper.m_Computer_Spring;
        public InputAction @Ability => m_Wrapper.m_Computer_Ability;
        public InputAction @Skip => m_Wrapper.m_Computer_Skip;
        public InputAction @Pause => m_Wrapper.m_Computer_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Computer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ComputerActions set) { return set.Get(); }
        public void SetCallbacks(IComputerActions instance)
        {
            if (m_Wrapper.m_ComputerActionsCallbackInterface != null)
            {
                @LeftFlipper.started -= m_Wrapper.m_ComputerActionsCallbackInterface.OnLeftFlipper;
                @LeftFlipper.performed -= m_Wrapper.m_ComputerActionsCallbackInterface.OnLeftFlipper;
                @LeftFlipper.canceled -= m_Wrapper.m_ComputerActionsCallbackInterface.OnLeftFlipper;
                @RightFlipper.started -= m_Wrapper.m_ComputerActionsCallbackInterface.OnRightFlipper;
                @RightFlipper.performed -= m_Wrapper.m_ComputerActionsCallbackInterface.OnRightFlipper;
                @RightFlipper.canceled -= m_Wrapper.m_ComputerActionsCallbackInterface.OnRightFlipper;
                @Spring.started -= m_Wrapper.m_ComputerActionsCallbackInterface.OnSpring;
                @Spring.performed -= m_Wrapper.m_ComputerActionsCallbackInterface.OnSpring;
                @Spring.canceled -= m_Wrapper.m_ComputerActionsCallbackInterface.OnSpring;
                @Ability.started -= m_Wrapper.m_ComputerActionsCallbackInterface.OnAbility;
                @Ability.performed -= m_Wrapper.m_ComputerActionsCallbackInterface.OnAbility;
                @Ability.canceled -= m_Wrapper.m_ComputerActionsCallbackInterface.OnAbility;
                @Skip.started -= m_Wrapper.m_ComputerActionsCallbackInterface.OnSkip;
                @Skip.performed -= m_Wrapper.m_ComputerActionsCallbackInterface.OnSkip;
                @Skip.canceled -= m_Wrapper.m_ComputerActionsCallbackInterface.OnSkip;
                @Pause.started -= m_Wrapper.m_ComputerActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_ComputerActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_ComputerActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_ComputerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftFlipper.started += instance.OnLeftFlipper;
                @LeftFlipper.performed += instance.OnLeftFlipper;
                @LeftFlipper.canceled += instance.OnLeftFlipper;
                @RightFlipper.started += instance.OnRightFlipper;
                @RightFlipper.performed += instance.OnRightFlipper;
                @RightFlipper.canceled += instance.OnRightFlipper;
                @Spring.started += instance.OnSpring;
                @Spring.performed += instance.OnSpring;
                @Spring.canceled += instance.OnSpring;
                @Ability.started += instance.OnAbility;
                @Ability.performed += instance.OnAbility;
                @Ability.canceled += instance.OnAbility;
                @Skip.started += instance.OnSkip;
                @Skip.performed += instance.OnSkip;
                @Skip.canceled += instance.OnSkip;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public ComputerActions @Computer => new ComputerActions(this);
    private int m_ComputerSchemeIndex = -1;
    public InputControlScheme ComputerScheme
    {
        get
        {
            if (m_ComputerSchemeIndex == -1) m_ComputerSchemeIndex = asset.FindControlSchemeIndex("Computer");
            return asset.controlSchemes[m_ComputerSchemeIndex];
        }
    }
    public interface IComputerActions
    {
        void OnLeftFlipper(InputAction.CallbackContext context);
        void OnRightFlipper(InputAction.CallbackContext context);
        void OnSpring(InputAction.CallbackContext context);
        void OnAbility(InputAction.CallbackContext context);
        void OnSkip(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
